/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_mathemator_demo_NativeExample */

#ifndef _Included_ru_mathemator_demo_NativeExample
#define _Included_ru_mathemator_demo_NativeExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_mathemator_demo_NativeExample
 * Method:    sayHelloFromC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_mathemator_demo_NativeExample_sayHelloFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
