version: '3'

services:
  rabbitmq:
    image: "rabbitmq:4-management"
    container_name: rabbitmq
    ports:
      - "15672:15672"  # Интерфейс для управления RabbitMQ (HTTP API)
      - "5672:5672"    # Основной порт для подключения клиентов
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
    driver: local
